project:
  type: website
  output-dir: docs

website:
  title: "BSC6926-B53B Spring 2025"
  navbar:
    left:
    - text: "Syllabus"
      href: sylb.html
    - text: "Readings"
      href: readings.html     
    - text: "Computer setup"
      href: comp.html
    - text: "Useful functions"
      href: usefulfx.html
    - text: 'WS 1'
      href: ws1.qmd
    - text: 'WS 2'
      href: ws2.qmd
    - text: 'WS 3'
      href: ws3.qmd
    - text: 'WS 4'
      href: ws4.qmd
    right:
    - text: 'Assignment'
      href: asmt.qmd

format:
  html:
    theme: yeti
    highlight: haddock
    css: styles.css



